import Link from 'next/link';
import type { Metadata } from 'next';
import SeoJsonLd from '@/components/SeoJsonLd';
import { getPublicSiteMedia, getPublicSiteSettings } from '@/lib/site-settings';
import { getPublicContentLocalized, getPublicContentCovers } from '@/lib/content';
export const metadata: Metadata = { title:'Kari Do Canto | Artesanía con Afecto', description:'Cursos, proyectos, consejos y paso a paso de artesanía para crear con tus propias manos.', alternates:{canonical:'https://karidocanto.com.br/es', languages:{'pt-BR':'https://karidocanto.com.br/','es':'https://karidocanto.com.br/es'}} };
export default async function HomeEs(){
 const [settings,posts,courses,media]=await Promise.all([getPublicSiteSettings(['cursos_title','cursos_description','blog_title','blog_description']),getPublicContentLocalized('blog','es-LA'),getPublicContentLocalized('curso','es-LA'),getPublicSiteMedia(['home-hero','home-about'])]);
 const [postMedia,courseMedia]=await Promise.all([getPublicContentCovers('blog',posts.map(p=>p.slug)),getPublicContentCovers('curso',courses.map(c=>c.slug))]);
 const hero=media['home-hero']?.url||'/images/hero.webp', about=media['home-about']?.url||'/images/about.webp';
 return <><SeoJsonLd type="WebSite" name="Kari Do Canto | Artesanía con Afecto" description="Cursos, proyectos y paso a paso para crear con tus propias manos." url="/es" image="/api/og-image"/><main>
 <section className="hero"><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow">Artesanía · Hogar · Afecto</span><h1>Crea para tu hogar <em>con amor y afecto.</em></h1><p>Ideas, cursos y paso a paso para transformar materiales sencillos en piezas hechas por tus manos — para decorar, organizar, regalar y hacer que tu hogar sea aún más tuyo.</p><div className="actions"><Link className="btn primary" href="/es/cursos">CONOCE LOS CURSOS</Link><Link className="btn" href="/es/sobre">CONOCE A KARI</Link></div></div><div className="hero-photo"><img src={hero} alt="Kari creando una pieza artesanal" width="554" height="350" fetchPriority="high"/></div></div></section>
 <section className="trust"><div className="container trust-grid"><div className="trust-item"><div className="trust-icon">♡</div><div><b>Hecho con afecto</b><span>Proyectos pensados para llevar belleza y significado a los pequeños detalles del hogar.</span></div></div><div className="trust-item"><div className="trust-icon">✂</div><div><b>Aprende haciendo</b><span>Clases y contenidos claros para crear a tu ritmo, con seguridad y placer.</span></div></div><div className="trust-item"><div className="trust-icon">⌂</div><div><b>Para tu hogar</b><span>Piezas para decorar, organizar, renovar ambientes y regalar a quienes amas.</span></div></div><div className="trust-item"><div className="trust-icon">✦</div><div><b>Experiencia de Kari</b><span>Una trayectoria en televisión convertida en inspiración para crear con tus propias manos.</span></div></div></div></section>
 <section className="section"><div className="container"><div className="section-head"><span className="eyebrow">Aprende a tu ritmo</span><h2>{settings.cursos_title || 'Cursos de artesanía'}</h2><p>{settings.cursos_description || 'Elige una técnica, aprende el proceso y descubre nuevas posibilidades para crear con tus propias manos.'}</p></div><div className="grid4">{courses.slice(0,4).map(c=><article className="card" key={c.id}><img src={courseMedia[`course:${c.slug}:cover`]?.url||'/images/course-feltro.webp'} alt={c.title}/><div className="card-body"><span className="tag">{c.category}</span><h3>{c.title}</h3><p>{c.summary}</p><Link className="more" href={`/es/cursos/${c.slug}`}>CONOCER CURSO →</Link></div></article>)}</div></div></section>
 <section className="section alt"><div className="container split"><div><span className="eyebrow">Conoce a Kari</span><h2>Una historia hecha a mano</h2><p>Una trayectoria que une televisión, creatividad, artesanía y el placer de enseñar.</p><Link className="btn" href="/es/sobre">CONOCE MI HISTORIA</Link></div><img src={about} alt="Kari do Canto en un ambiente de artesanía" loading="lazy"/></div></section>
 <section className="section"><div className="container"><div className="section-head"><span className="eyebrow">Contenido gratuito</span><h2>{settings.blog_title || 'Blog'}</h2><p>{settings.blog_description || 'Consejos, técnicas, inspiración y paso a paso para aprender y crear proyectos cada vez más bonitos.'}</p></div><div className="grid4">{posts.slice(0,4).map(p=><article className="card" key={p.id}><img src={postMedia[`blog:${p.slug}:cover`]?.url||'/images/blog-cestinho.webp'} alt={p.title}/><div className="card-body"><span className="tag">{p.category}</span><h3>{p.title}</h3><p>{p.summary}</p><Link className="more" href={`/es/blog/${p.slug}`}>LEER ARTÍCULO →</Link></div></article>)}</div></div></section>
 </main></>;
}
