import Link from 'next/link';
import type { Metadata } from 'next';
import SeoJsonLd from '@/components/SeoJsonLd';
import { getPublicSiteMedia, getPublicSiteSettings } from '@/lib/site-settings';
import { getPublicContentLocalized, getPublicContentCovers } from '@/lib/content';
import YouTubeGallery from '@/components/YouTubeGallery';
import InstagramProfile from '@/components/InstagramProfile';
import BlogCarousel from '@/components/BlogCarousel';
export const metadata: Metadata = { title:'Kari Do Canto | Artesanía con Afecto', description:'Cursos, proyectos, consejos y paso a paso de artesanía para crear con tus propias manos.', alternates:{canonical:'https://karidocanto.com.br/es',languages:{'pt-BR':'https://karidocanto.com.br/','es':'https://karidocanto.com.br/es'}} };
export default async function HomeEs(){
 const [settings,posts,courses,media]=await Promise.all([getPublicSiteSettings(['cursos_title','cursos_description','cursos_title_es','cursos_description_es','cursos_enabled','blog_title','blog_description','blog_title_es','blog_description_es','blog_enabled','youtube_url_es','youtube_es_video_id','youtube_es_video_title','youtube_es_video_enabled','youtube_es_video_id_2','youtube_es_video_title_2','youtube_es_video_enabled_2','youtube_es_video_id_3','youtube_es_video_title_3','youtube_es_video_enabled_3','youtube_es_video_id_4','youtube_es_video_title_4','youtube_es_video_enabled_4','youtube_es_video_id_5','youtube_es_video_title_5','youtube_es_video_enabled_5']),getPublicContentLocalized('blog','es-LA'),getPublicContentLocalized('curso','es-LA'),getPublicSiteMedia(['home-hero','home-about'])]);
 const [postMedia,courseMedia]=await Promise.all([getPublicContentCovers('blog',posts.map(p=>p.slug)),getPublicContentCovers('curso',courses.map(c=>c.slug))]);
 const hero=media['home-hero']?.url||'/images/hero.webp',about=media['home-about']?.url||'/images/about.webp';
 const cursosEnabled=settings.cursos_enabled!=='false',blogEnabled=settings.blog_enabled!=='false';
 const normalizeVideoId=(value:string)=>{const match=value.trim().match(/(?:v=|youtu\.be\/|youtube\.com\/shorts\/|youtube\.com\/embed\/)([A-Za-z0-9_-]{11})/);return match?.[1]??value.trim().replace(/[^A-Za-z0-9_-]/g,'').slice(0,11);};
 const youtubeVideos=Array.from({length:5},(_,index)=>{const suffix=index===0?'':`_${index+1}`;const videoId=normalizeVideoId(settings[`youtube_es_video_id${suffix}`]||'');return {title:settings[`youtube_es_video_title${suffix}`]||`Video ${index+1}`,videoId,enabled:settings[`youtube_es_video_enabled${suffix}`]!=='false'&&Boolean(videoId)};}).filter(v=>v.enabled);
 const youtubeChannel=settings.youtube_url_es||'https://www.youtube.com/@KaridoCanto';
 return <><SeoJsonLd type="WebSite" name="Kari Do Canto | Artesanía con Afecto" description="Cursos, proyectos y paso a paso para crear con tus propias manos." url="/es" image="/api/og-image"/><main>
 <section className="hero"><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow">Artesanía · Hogar · Afecto</span><h1>Crea para tu hogar <em>con amor y afecto.</em></h1><p>Ideas, cursos y paso a paso para transformar materiales sencillos en piezas hechas por tus manos — para decorar, organizar, regalar y hacer que tu hogar sea aún más tuyo.</p><div className="actions"><Link className="btn primary" href="/es/cursos">CONOCE LOS CURSOS</Link><Link className="btn" href="/es/sobre">CONOCE A KARI</Link></div></div><div className="hero-photo"><img src={hero} alt="Kari creando una pieza artesanal" width="554" height="350" fetchPriority="high"/></div></div></section>
 <section className="trust"><div className="container trust-grid"><div className="trust-item"><div className="trust-icon">♡</div><div><b>Hecho con afecto</b><span>Proyectos pensados para llevar belleza y significado a los pequeños detalles del hogar.</span></div></div><div className="trust-item"><div className="trust-icon">✂</div><div><b>Aprende haciendo</b><span>Clases y contenidos claros para crear a tu ritmo, con seguridad y placer.</span></div></div><div className="trust-item"><div className="trust-icon">⌂</div><div><b>Para tu hogar</b><span>Piezas para decorar, organizar, renovar ambientes y regalar a quienes amas.</span></div></div><div className="trust-item"><div className="trust-icon">✦</div><div><b>Experiencia de Kari</b><span>Una trayectoria en televisión convertida en inspiración para crear con tus propias manos.</span></div></div></div></section>
 <section className="section" hidden={!blogEnabled}><div className="container"><div className="section-head"><span className="eyebrow">Contenido gratuito</span><h2>{settings.blog_title_es||'Consejos y paso a paso para el hogar'}</h2><p>{settings.blog_description_es||'Aprende una técnica, elige tus materiales y encuentra inspiración para tu próximo proyecto.'}</p></div><BlogCarousel posts={posts} media={postMedia} locale="es"/></div></section>
 <section className="section video-section"><div className="container"><div className="section-head"><span className="eyebrow">Videos de Kari</span><h2 className="serif">Aprende, mira y crea.</h2><p>Contenido de YouTube en una galería ligera: el reproductor solo se carga cuando decides mirar.</p></div><YouTubeGallery videos={youtubeVideos} channel={youtubeChannel}/></div></section>
 <section className="section social-section"><div className="container social-grid"><div><div className="section-head social-head"><span className="eyebrow">Sigue a Kari</span><h2 className="serif">Más ideas para crear con afecto.</h2><p>Continúa acompañando a Kari en las redes y descubre nuevos proyectos, consejos e inspiraciones para tu hogar.</p></div><div className="social-links"><a className="btn primary" href="https://www.youtube.com/@KaridoCanto" target="_blank" rel="noreferrer">YOUTUBE ↗</a><a className="btn" href="https://www.instagram.com/karidocanto.craft/" target="_blank" rel="noreferrer">INSTAGRAM ↗</a></div></div><InstagramProfile/></div></section>
 <section className="section" hidden={!cursosEnabled}><div className="container"><div className="section-head"><span className="eyebrow">Aprende a tu ritmo</span><h2>{settings.cursos_title_es||'Cursos de artesanía'}</h2><p>{settings.cursos_description_es||'Elige una técnica, aprende el proceso y descubre nuevas posibilidades para crear con tus propias manos.'}</p></div><div className="grid4">{courses.slice(0,4).map(c=><article className="card" key={c.id}><img src={courseMedia[`course:${c.slug}:cover`]?.url||'/images/course-feltro.webp'} alt={c.title}/><div className="card-body"><span className="tag">{c.category}</span><h3>{c.title}</h3><p>{c.summary}</p><Link className="more" href={`/es/cursos/${c.slug}`}>CONOCER CURSO →</Link></div></article>)}</div></div></section>
 <section className="story"><div className="container story-grid"><div className="story-photo"><img src={about} alt="Kari do Canto en un ambiente de artesanía" width="350" height="165" loading="lazy"/></div><div className="story-copy"><span className="eyebrow">Kari Do Canto</span><h2 className="serif">Una casa bonita también cuenta historias.</h2><p>Una trayectoria que une televisión, creatividad, artesanía y el placer de enseñar.</p><Link className="btn primary" href="/es/sobre">CONOCE LA HISTORIA</Link></div></div></section>
 </main></>;
}
