'use client';
import {useEffect,useState} from 'react'; import {getSupabaseBrowserClient} from '@/lib/supabase';
type Comment={id:string;slug:string;locale:'pt-BR'|'es-LA';name:string;email:string;comment:string;status:string;created_at:string};
export default function AdminCommentsManager(){const [comments,setComments]=useState<Comment[]>([]);const [locale,setLocale]=useState<'pt-BR'|'es-LA'>('pt-BR');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
async function load(){const s=getSupabaseBrowserClient();if(!s)return;const {data}=await s.auth.getSession();if(!data.session)return;const r=await fetch(`/api/blog-comments?slug=all&locale=${locale}`,{headers:{Authorization:`Bearer ${data.session.access_token}`},cache:'no-store'});const d=await r.json().catch(()=>({}));setComments((d.comments||[]) as Comment[])}
useEffect(()=>{load()},[locale]);
async function moderate(id:string,status:'approved'|'rejected'|'pending'){const s=getSupabaseBrowserClient();if(!s)return;const {data}=await s.auth.getSession();if(!data.session){setMessage('Sessão expirada.');return}setBusy(true);const r=await fetch('/api/blog-comments',{method:'PATCH',headers:{Authorization:`Bearer ${data.session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({id,status})});const d=await r.json().catch(()=>({}));setMessage(r.ok?'Atualizado.':`Erro: ${d.error||'Falha.'}`);await load();setBusy(false)}
async function remove(id:string){if(!window.confirm('Excluir este comentário definitivamente?'))return;const s=getSupabaseBrowserClient();if(!s)return;const {data}=await s.auth.getSession();if(!data.session)return;setBusy(true);const r=await fetch(`/api/blog-comments?id=${encodeURIComponent(id)}`,{method:'DELETE',headers:{Authorization:`Bearer ${data.session.access_token}`}});setMessage(r.ok?'Comentário excluído.':'Não foi possível excluir.');await load();setBusy(false)}
return <section className="media-panel"><div className="admin-panel-head"><div><span className="eyebrow">Comunidade</span><h2 className="serif">Comentários do blog</h2><p>Modere os comentários antes que aparezcan publicamente.</p></div></div><div className="admin-tabs"><button className={locale==='pt-BR'?'active':''} onClick={()=>setLocale('pt-BR')}>🇧🇷 Português</button><button className={locale==='es-LA'?'active':''} onClick={()=>setLocale('es-LA')}>🇪🇸 Español LATAM</button></div><div className="card"><div className="card-body"><span className="tag">{comments.filter(c=>c.status==='pending').length} pendentes</span>{comments.length===0&&<p>Nenhum comentário neste idioma.</p>}{comments.map(c=><article key={c.id} style={{borderBottom:'1px solid #e5ddd2',padding:'18px 0'}}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><strong>{c.name}</strong><small>{c.email} · {new Date(c.created_at).toLocaleString(locale==='es-LA'?'es-LA':'pt-BR')}</small></div><small><b>{c.status}</b> · /{locale==='es-LA'?'es/':''}blog/{c.slug}</small><p>{c.comment}</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{c.status!=='approved'&&<button className="btn primary" disabled={busy} onClick={()=>moderate(c.id,'approved')}>APROVAR</button>}{c.status!=='rejected'&&<button className="btn" disabled={busy} onClick={()=>moderate(c.id,'rejected')}>REJEITAR</button>}{c.status!=='pending'&&<button className="btn" disabled={busy} onClick={()=>moderate(c.id,'pending')}>PENDENTE</button>}<button className="btn" disabled={busy} onClick={()=>remove(c.id)}>EXCLUIR</button></div></article>)}</div></div>{message&&<p className="form-status success">{message}</p>}</section>}
