import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import LeadCapture from '@/components/LeadCapture';
import SeoJsonLd from '@/components/SeoJsonLd';
import YouTubeGallery from '@/components/YouTubeGallery';
import { getPublicContentBySlug, getPublicContentMedia } from '@/lib/content';

export const dynamic = 'force-dynamic';
const base='https://karidocanto.com.br';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const c=await getPublicContentBySlug('curso',slug);if(!c)return {title:'Curso não encontrado',robots:{index:false,follow:false}};const media=await getPublicContentMedia('curso',slug);const image=media[`course:${slug}:cover`]?.url||'/images/course-feltro.webp';return {title:c.title,description:c.summary,alternates:{canonical:`${base}/cursos/${slug}`},openGraph:{title:c.title,description:c.summary,url:`${base}/cursos/${slug}`,type:'website',images:[{url:image,alt:c.title}]},twitter:{card:'summary_large_image',title:c.title,description:c.summary,images:[image]}}}
const normalizeVideoId=(value:string)=>{const match=value.trim().match(/(?:v=|youtu\.be\/|youtube\.com\/shorts\/|youtube\.com\/embed\/)([A-Za-z0-9_-]{11})/);return match?.[1]??value.trim().replace(/[^A-Za-z0-9_-]/g,'').slice(0,11)};
export default async function Curso({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const c=await getPublicContentBySlug('curso',slug);if(!c)notFound();const media=await getPublicContentMedia('curso',slug);const image=media[`course:${slug}:cover`]?.url||'/images/course-feltro.webp';const alt=media[`course:${slug}:cover`]?.alt||c.title;return <><SeoJsonLd type="Course" name={c.title} description={c.summary} url={`/cursos/${slug}`} image={image} breadcrumbs={[{name:'Início',item:'/'},{name:'Cursos',item:'/cursos'},{name:c.title,item:`/cursos/${slug}`}]}/><section className="pageHero"><span className="eyebrow">Curso online · {c.category}</span><h1 className="serif">{c.title}</h1><p>{c.summary}</p></section><section className="article"><img src={image} alt={alt} loading="eager" decoding="async"/><h2>O que você vai encontrar</h2><ul>{c.steps.map((step,i)=><li key={i}>{step}</li>)}</ul><h2>Aprenda fazendo</h2><p>{c.content}</p></section>{c.video_url && <section className="section video-section"><div className="container"><div className="section-head"><span className="eyebrow">Vídeo do curso</span><h2 className="serif">Aprenda com a Kari.</h2></div><YouTubeGallery videos={[{title:c.title,videoId:normalizeVideoId(c.video_url),enabled:true}]} /></div></section>}<section className="section alt"><div className="container"><LeadCapture courseSlug={slug} courseTitle={c.title} source="course-page" /></div></section></>}
