import Link from 'next/link';
import { notFound } from 'next/navigation';

const posts: Record<string,{title:string;tag:string;image:string;intro:string;steps:string[]}>={
  'cestinho-de-tecido':{title:'Cestinho de tecido: passo a passo completo',tag:'Passo a passo',image:'/images/blog-cestinho.jpg',intro:'Um projeto delicado e funcional para praticar montagem, composição e acabamento.',steps:['Separe tecido, manta e os materiais indicados para a estrutura do cestinho.','Prepare as partes do projeto e marque as referências antes da montagem.','Monte as camadas com atenção ao alinhamento e às margens de costura.','Finalize as bordas e revise o acabamento antes de virar a peça.']},
  'como-escolher-linhas':{title:'Como escolher as melhores linhas',tag:'Dicas de artesanato',image:'/images/blog-linhas.jpg',intro:'A escolha da linha influencia a costura, o acabamento e até a aparência final da peça.',steps:['Observe o tipo de tecido ou material que será trabalhado.','Considere espessura, resistência e finalidade da peça.','Faça um pequeno teste antes de iniciar o projeto completo.','Guarde os materiais organizados por tipo para facilitar os próximos projetos.']},
  'pintura-em-madeira':{title:'Pintura em madeira: técnicas e cuidados',tag:'Técnicas',image:'/images/blog-madeira.jpg',intro:'Preparação e acabamento fazem diferença quando a ideia é criar uma peça bonita e durável.',steps:['Limpe e prepare a superfície antes de aplicar qualquer produto.','Faça testes de cor e cobertura em uma área de amostra.','Aplique camadas finas, respeitando o tempo de secagem.','Proteja o trabalho final com o acabamento adequado ao projeto.']},
  'flores-de-feltro':{title:'Flores de feltro: ideias para criar',tag:'Inspiração',image:'/images/blog-feltro.jpg',intro:'Flores de feltro são versáteis e permitem brincar com cores, tamanhos e composições.',steps:['Escolha uma combinação de cores que converse com o projeto.','Corte as formas com precisão e mantenha os moldes organizados.','Monte as pétalas criando volume aos poucos.','Use as flores em arranjos, acessórios, decoração ou presentes.']},
};
export function generateStaticParams(){return Object.keys(posts).map(slug=>({slug}))}
export function generateMetadata({params}:{params:{slug:string}}){const p=posts[params.slug];return p?{title:p.title,description:p.intro}:{title:'Blog'}}
export default function Post({params}:{params:{slug:string}}){const p=posts[params.slug];if(!p)notFound();return <><section className="pageHero"><span className="eyebrow">{p.tag}</span><h1 className="serif">{p.title}</h1><p>{p.intro}</p></section><article className="article"><img src={p.image} alt={p.title}/><h2>Materiais e preparação</h2><p>Antes de começar, organize a mesa, separe os materiais e reserve um tempo para observar o projeto. Trabalhar com calma ajuda a perceber detalhes que fazem diferença no resultado.</p><h2>Passo a passo</h2><ol>{p.steps.map((step,i)=><li key={i}>{step}</li>)}</ol><h2>Dica da Kari</h2><p>O acabamento não é apenas a última etapa: ele deve ser pensado desde o começo. Pequenos cuidados durante a execução deixam a peça mais bonita e facilitam a finalização.</p><div className="actions"><Link className="btn primary" href="/cursos">CONHEÇA OS CURSOS</Link><Link className="btn" href="/blog">VOLTAR AO BLOG</Link></div></article></>}
