import Link from 'next/link';
import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import SeoJsonLd from '@/components/SeoJsonLd';
import { getPublicBlogMedia } from '@/lib/site-settings';

const posts: Record<string,{title:string;tag:string;image:string;intro:string;steps:string[]}>= {
  'cestinho-de-tecido':{title:'Cestinho de tecido: passo a passo completo',tag:'Passo a passo',image:'/images/blog-cestinho.webp',intro:'Um projeto delicado e funcional para praticar montagem, composição e acabamento.' ,steps:['Separe tecido, manta e os materiais indicados para a estrutura do cestinho.','Prepare as partes do projeto e marque as referências antes da montagem.','Monte as camadas com atenção ao alinhamento e às margens de costura.','Finalize as bordas e revise o acabamento antes de virar a peça.']},
  'como-escolher-linhas':{title:'Como escolher as melhores linhas',tag:'Dicas de artesanato',image:'/images/blog-linhas.webp',intro:'A escolha da linha influencia a costura, o acabamento e até a aparência final da peça.',steps:['Observe o tipo de tecido ou material que será trabalhado.','Considere espessura, resistência e finalidade da peça.','Faça um pequeno teste antes de iniciar o projeto completo.','Guarde os materiais organizados por tipo para facilitar os próximos projetos.']},
  'pintura-em-madeira':{title:'Pintura em madeira: técnicas e cuidados',tag:'Técnicas',image:'/images/blog-madeira.webp',intro:'Preparação e acabamento fazem diferença quando a ideia é criar uma peça bonita e durável.',steps:['Limpe e prepare a superfície antes de aplicar qualquer produto.','Faça testes de cor e cobertura em uma área de amostra.','Aplique camadas finas, respeitando o tempo de secagem.','Proteja o trabalho final com o acabamento adequado ao projeto.']},
  'flores-de-feltro':{title:'Flores de feltro: ideias para criar',tag:'Inspiração',image:'/images/blog-feltro.webp',intro:'Flores de feltro são versáteis e permitem brincar com cores, tamanhos e composições.',steps:['Escolha uma combinação de cores que converse com o projeto.','Corte as formas com precisão e mantenha os moldes organizados.','Monte as pétalas criando volume aos poucos.','Use as flores em arranjos, acessórios, decoração ou presentes.']},
};

const base='https://karidocanto.com.br';
export function generateStaticParams(){return Object.keys(posts).map(slug=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=posts[slug];if(!p)return {title:'Artigo não encontrado',robots:{index:false,follow:false}};const url=`${base}/blog/${slug}`;const media=await getPublicBlogMedia(slug);const cover=media[`blog:${slug}:cover`]?.url||p.image;return {title:p.title,description:p.intro,alternates:{canonical:url},openGraph:{title:p.title,description:p.intro,url,type:'article',images:[{url:cover,alt:p.title}]},twitter:{card:'summary_large_image',title:p.title,description:p.intro,images:[cover]}}}
export default async function Post({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=posts[slug];if(!p)notFound();const media=await getPublicBlogMedia(slug);const cover=media[`blog:${slug}:cover`]?.url||p.image;const inside=media[`blog:${slug}:inside`]?.url;const coverAlt=media[`blog:${slug}:cover`]?.alt||p.title;const insideAlt=media[`blog:${slug}:inside`]?.alt||`${p.title} — imagem do projeto`;return <><SeoJsonLd type="Article" name={p.title} description={p.intro} url={`/blog/${slug}`} image={cover} breadcrumbs={[{name:'Início',item:'/'},{name:'Blog',item:'/blog'},{name:p.title,item:`/blog/${slug}`}]}/><section className="pageHero"><span className="eyebrow">{p.tag}</span><h1 className="serif">{p.title}</h1><p>{p.intro}</p></section><article className="article"><img src={cover} alt={coverAlt} loading="eager" decoding="async"/><h2>Materiais e preparação</h2><p>Antes de começar, organize a mesa, separe os materiais e reserve um tempo para observar o projeto. Trabalhar com calma ajuda a perceber detalhes que fazem diferença no resultado.</p>{inside && <figure className="article-image"><img src={inside} alt={insideAlt} loading="lazy" decoding="async"/><figcaption>Imagem do projeto — Kari Do Canto</figcaption></figure>}<h2>Passo a passo</h2><ol>{p.steps.map((step,i)=><li key={i}>{step}</li>)}</ol><h2>Dica da Kari</h2><p>O acabamento não é apenas a última etapa: ele deve ser pensado desde o começo. Pequenos cuidados durante a execução deixam a peça mais bonita e facilitam a finalização.</p><div className="actions">{media[`blog:${slug}:download`]?.url && <a className="btn primary" href={media[`blog:${slug}:download`].url} download={media[`blog:${slug}:download`].filename || 'molde.zip'}>BAIXAR MOLDE (ZIP) ↓</a>}<Link className="btn" href="/cursos">CONHEÇA OS CURSOS</Link><Link className="btn" href="/blog">VOLTAR AO BLOG</Link></div></article></>}
