import Link from 'next/link';
import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import SeoJsonLd from '@/components/SeoJsonLd';
import { getPublicContentBySlug, getPublicContentMedia } from '@/lib/content';

export const dynamic = 'force-dynamic';
const base='https://karidocanto.com.br';

export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=await getPublicContentBySlug('blog',slug);if(!p)return {title:'Artigo não encontrado',robots:{index:false,follow:false}};const media=await getPublicContentMedia('blog',slug);const cover=media[`blog:${slug}:cover`]?.url||'/images/blog-cestinho.webp';return {title:p.title,description:p.summary,alternates:{canonical:`${base}/blog/${slug}`},openGraph:{title:p.title,description:p.summary,url:`${base}/blog/${slug}`,type:'article',images:[{url:cover,alt:p.title}]},twitter:{card:'summary_large_image',title:p.title,description:p.summary,images:[cover]}}}

export default async function Post({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=await getPublicContentBySlug('blog',slug);if(!p)notFound();const media=await getPublicContentMedia('blog',slug);const cover=media[`blog:${slug}:cover`]?.url||'/images/blog-cestinho.webp';const inside=media[`blog:${slug}:inside`]?.url;const coverAlt=media[`blog:${slug}:cover`]?.alt||p.title;const insideAlt=media[`blog:${slug}:inside`]?.alt||`${p.title} — imagem do projeto`;return <><SeoJsonLd type="Article" name={p.title} description={p.summary} url={`/blog/${slug}`} image={cover} breadcrumbs={[{name:'Início',item:'/'},{name:'Blog',item:'/blog'},{name:p.title,item:`/blog/${slug}`}]}/><section className="pageHero"><span className="eyebrow">{p.category}</span><h1 className="serif">{p.title}</h1><p>{p.summary}</p></section><article className="article"><img src={cover} alt={coverAlt} loading="eager" decoding="async"/><h2>Materiais e preparação</h2><p>{p.content}</p>{inside && <figure className="article-image"><img src={inside} alt={insideAlt} loading="lazy" decoding="async"/><figcaption>Imagem do projeto — Kari Do Canto</figcaption></figure>}<h2>Passo a passo</h2><ol>{p.steps.map((step,i)=><li key={i}>{step}</li>)}</ol><h2>Dica da Kari</h2><p>O acabamento não é apenas a última etapa: ele deve ser pensado desde o começo. Pequenos cuidados durante a execução deixam a peça mais bonita e facilitam a finalização.</p><div className="actions">{media[`blog:${slug}:download`]?.url && <a className="btn primary" href={media[`blog:${slug}:download`].url} download={media[`blog:${slug}:download`].filename || 'molde.zip'}>BAIXAR MOLDE (ZIP) ↓</a>}<Link className="btn" href="/cursos">CONHEÇA OS CURSOS</Link><Link className="btn" href="/blog">VOLTAR AO BLOG</Link></div></article></>}
